version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-passin
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passin
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
    networks:
      - passin

  api-passin:
    build:
      context: .
    container_name: api-passin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - passin
  
networks:
  passin:
    driver: bridge