name: CI

on:
  push:
    branches:
      - main

jobs:
  buid-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo "$GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      -name: Buld docker image
        run: docker build -t luizhduarte/passIn:${{ steps.generate_sha.outputs.sha}} .